apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: techpoint247/flask-to-do-app:latest  # Use local image
          #imagePullPolicy: Never   # Prevent Kubernetes from pulling from Docker Hub
          ports:
            - containerPort: 8000
