name: deploy to AWS EC2

on: 
  push:
    branches:
      - main

jobs: 
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: set up ssh key
        run: |
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: deploy ec2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} >> 'EOF'
          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
          docker stop flask-app || true
          docker rm flask-app || true
          docker pull techpoint247/flask-to-do-app:latest
          docker run -d -p 5000:5000 --name flask-app techpoint247/flask-to-do-app:latest
          EOF
